import React from 'react';
import { Card, TactileButton } from '../ui/Card';
import { FileText, Copy, CheckCircle2, Smile, Activity } from 'lucide-react';
import { motion } from 'framer-motion';
import { ScrollReveal } from '../ui/ScrollReveal';

const SummaryCard = ({ group, time, tags, points, generatedBy, copyText }: any) => (
  <Card className="mb-4 hover:shadow-md transition-shadow">
    <div className="flex justify-between items-start mb-4">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-stone-100 flex items-center justify-center font-bold text-stone-600">
          GR
        </div>
        <div>
          <h4 className="font-bold text-stone-800">{group}</h4>
          <div className="text-xs text-stone-500 flex items-center gap-2">
            <span>45 members</span>
            <span className="w-1 h-1 bg-stone-300 rounded-full" />
            <span>Today • {time}</span>
          </div>
        </div>
      </div>
      <div className="flex gap-2">
         {tags.map((t: string) => (
           <span key={t} className="px-2 py-1 bg-stone-100 text-[10px] font-bold uppercase text-stone-500 rounded-md tracking-wide">
             {t}
           </span>
         ))}
      </div>
    </div>
    
    <div className="space-y-2 mb-6 pl-4 border-l-2 border-orange-100">
      {points.map((p: string, i: number) => (
        <div key={i} className="flex items-start gap-2 text-sm text-stone-600">
          <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-orange-400 flex-shrink-0" />
          <p>{p}</p>
        </div>
      ))}
    </div>

    <div className="flex justify-between items-center border-t border-stone-50 pt-4">
      <span className="text-xs text-stone-400 font-medium">{generatedBy}</span>
      <button className="text-xs font-semibold text-orange-600 flex items-center gap-1.5 hover:text-orange-700 transition-colors">
        <Copy size={14} /> {copyText}
      </button>
    </div>
  </Card>
);

export const SummariesFeature: React.FC<{ lang: 'en' | 'pt' }> = ({ lang }) => {
  const t = {
    en: {
      badge: 'Smart Summaries',
      title: 'Turn chaos into',
      titleHighlight: 'clarity',
      subtitle: 'instantly.',
      description: "Don't read thousands of messages. MGM AI digests daily discussions, highlights actionable items, and identifies sentiment shifts automatically.",
      btnStart: 'Start summarizing',
      btnDemo: 'View demo',
      stats: { generated: 'Generated', actions: 'Actions', sentiment: 'Sentiment', insights: 'Insights', positive: 'Positive' },
      card1: {
         tags: ['Planning', 'Feedback'],
         points: ["Q1 objectives prioritized for next sprint.", "Approval flow redesigned to reduce friction.", "Team requested more clarity on marketing budget."]
      },
      card2: {
         tags: ['Launch', 'Sales'],
         points: ["Product launch confirmed for Dec 15th.", "Inbound campaign approved by stakeholders.", "Sales team reporting higher than average lead quality."]
      },
      generatedBy: 'Auto-generated by MGM AI',
      copyText: 'Copy for leadership',
      automation: { title: 'Automated Daily Digest', sub: 'Send to leaders at 6:00 PM', btn: 'Enable' }
    },
    pt: {
      badge: 'Resumos Inteligentes',
      title: 'Transforme caos em',
      titleHighlight: 'clareza',
      subtitle: 'instantaneamente.',
      description: "Não leia milhares de mensagens. A MGM AI digere discussões diárias, destaca itens acionáveis e identifica mudanças de sentimento automaticamente.",
      btnStart: 'Começar a resumir',
      btnDemo: 'Ver demo',
      stats: { generated: 'Gerados', actions: 'Ações', sentiment: 'Sentimento', insights: 'Insights', positive: 'Positivo' },
      card1: {
         tags: ['Planejamento', 'Feedback'],
         points: ["Objetivos do Q1 priorizados para o próximo sprint.", "Fluxo de aprovação redesenhado para reduzir atrito.", "Equipe pediu mais clareza no orçamento de marketing."]
      },
      card2: {
         tags: ['Lançamento', 'Vendas'],
         points: ["Lançamento do produto confirmado para 15 de Dez.", "Campanha de inbound aprovada pelos stakeholders.", "Time de vendas relatando qualidade de leads acima da média."]
      },
      generatedBy: 'Gerado auto. por MGM AI',
      copyText: 'Copiar p/ liderança',
      automation: { title: 'Digest Diário Automático', sub: 'Enviar para líderes às 18:00', btn: 'Ativar' }
    }
  }[lang];

  return (
    <div className="flex flex-col lg:flex-row gap-8 md:gap-16 items-center py-16 md:py-24">
      <div className="lg:w-1/3 space-y-6">
        <ScrollReveal>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-100 text-orange-700 text-xs font-bold uppercase tracking-wide">
            <FileText size={14} />
            <span>{t.badge}</span>
          </div>
        </ScrollReveal>
        
        <ScrollReveal delay={0.1}>
          <h2 className="text-4xl md:text-5xl font-bold text-stone-900 leading-tight">
            {t.title} <span className="text-orange-500">{t.titleHighlight}</span> {t.subtitle}
          </h2>
        </ScrollReveal>

        <ScrollReveal delay={0.2}>
          <p className="text-lg text-stone-600 leading-relaxed">
            {t.description}
          </p>
        </ScrollReveal>

        <ScrollReveal delay={0.3}>
          <div className="flex gap-4 pt-4">
             <TactileButton primary>{t.btnStart}</TactileButton>
             <TactileButton>{t.btnDemo}</TactileButton>
          </div>
        </ScrollReveal>
      </div>

      <div className="lg:w-2/3 w-full perspective-1000 mt-8 lg:mt-0">
        <motion.div 
          initial={{ rotateY: 0, x: 0, opacity: 0 }}
          whileInView={{ rotateY: -5, x: 0, opacity: 1 }}
          transition={{ duration: 1, ease: "easeOut" }}
          viewport={{ once: true, margin: "-100px" }}
          className="bg-stone-50 p-4 md:p-8 rounded-[2rem] border border-stone-200 shadow-2xl relative z-10"
        >
          {/* Stats Row */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
             {[
               { label: t.stats.generated, val: "4", icon: null },
               { label: t.stats.actions, val: "28", icon: null },
               { label: t.stats.sentiment, val: t.stats.positive, icon: <Smile size={20} className="text-emerald-500" /> },
               { label: t.stats.insights, val: "12", icon: <Activity size={16} className="text-orange-500" /> }
             ].map((item, i) => (
                <Card key={i} noPadding className="p-4 flex flex-col justify-between h-24">
                  <span className="text-[10px] text-stone-400 font-bold uppercase tracking-wider">{item.label}</span>
                  <div className="flex items-center gap-1 text-stone-800 font-bold text-xl lg:text-2xl">
                    {item.val} {item.icon}
                  </div>
                </Card>
             ))}
          </div>

          {/* Summaries Feed */}
          <div className="space-y-4">
            <SummaryCard 
              group="Group 42" 
              time="14:30" 
              tags={t.card1.tags} 
              points={t.card1.points} 
              generatedBy={t.generatedBy}
              copyText={t.copyText}
            />
            <SummaryCard 
              group="Group 15" 
              time="10:15" 
              tags={t.card2.tags} 
              points={t.card2.points} 
              generatedBy={t.generatedBy}
              copyText={t.copyText}
            />
          </div>
          
          {/* Automation Suggestion */}
          <motion.div 
            initial={{ y: 20, opacity: 0 }}
            whileInView={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.5 }}
            className="mt-6 p-4 bg-orange-50 border border-orange-100 rounded-xl flex items-center justify-between flex-wrap gap-2"
          >
             <div className="flex items-center gap-3">
               <div className="w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center text-orange-600">
                 <Activity size={16} />
               </div>
               <div>
                 <p className="text-sm font-bold text-stone-800">{t.automation.title}</p>
                 <p className="text-xs text-stone-500">{t.automation.sub}</p>
               </div>
             </div>
             <TactileButton className="text-xs py-1 px-3">{t.automation.btn}</TactileButton>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
};