import React from 'react';
import { Card, TactileButton } from '../ui/Card';
import { FileText, Copy, CheckCircle2, Smile, Activity } from 'lucide-react';
import { motion } from 'framer-motion';
import { ScrollReveal } from '../ui/ScrollReveal';

const SummaryCard = ({ group, time, tags, points }: any) => (
  <Card className="mb-4 hover:shadow-md transition-shadow">
    <div className="flex justify-between items-start mb-4">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-stone-100 flex items-center justify-center font-bold text-stone-600">
          GR
        </div>
        <div>
          <h4 className="font-bold text-stone-800">{group}</h4>
          <div className="text-xs text-stone-500 flex items-center gap-2">
            <span>45 members</span>
            <span className="w-1 h-1 bg-stone-300 rounded-full" />
            <span>Today • {time}</span>
          </div>
        </div>
      </div>
      <div className="flex gap-2">
         {tags.map((t: string) => (
           <span key={t} className="px-2 py-1 bg-stone-100 text-[10px] font-bold uppercase text-stone-500 rounded-md tracking-wide">
             {t}
           </span>
         ))}
      </div>
    </div>
    
    <div className="space-y-2 mb-6 pl-4 border-l-2 border-orange-100">
      {points.map((p: string, i: number) => (
        <div key={i} className="flex items-start gap-2 text-sm text-stone-600">
          <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-orange-400 flex-shrink-0" />
          <p>{p}</p>
        </div>
      ))}
    </div>

    <div className="flex justify-between items-center border-t border-stone-50 pt-4">
      <span className="text-xs text-stone-400 font-medium">Auto-generated by MGM AI</span>
      <button className="text-xs font-semibold text-orange-600 flex items-center gap-1.5 hover:text-orange-700 transition-colors">
        <Copy size={14} /> Copy for leadership
      </button>
    </div>
  </Card>
);

export const SummariesFeature: React.FC = () => {
  return (
    <div className="flex flex-col lg:flex-row gap-16 items-center py-24">
      <div className="lg:w-1/3 space-y-6">
        <ScrollReveal>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-100 text-orange-700 text-xs font-bold uppercase tracking-wide">
            <FileText size={14} />
            <span>Smart Summaries</span>
          </div>
        </ScrollReveal>
        
        <ScrollReveal delay={0.1}>
          <h2 className="text-4xl md:text-5xl font-bold text-stone-900 leading-tight">
            Turn chaos into <span className="text-orange-500">clarity</span> instantly.
          </h2>
        </ScrollReveal>

        <ScrollReveal delay={0.2}>
          <p className="text-lg text-stone-600 leading-relaxed">
            Don't read thousands of messages. MGM AI digests daily discussions, highlights actionable items, and identifies sentiment shifts automatically.
          </p>
        </ScrollReveal>

        <ScrollReveal delay={0.3}>
          <div className="flex gap-4 pt-4">
             <TactileButton primary>Start summarizing</TactileButton>
             <TactileButton>View demo</TactileButton>
          </div>
        </ScrollReveal>
      </div>

      <div className="lg:w-2/3 w-full perspective-1000">
        <motion.div 
          initial={{ rotateY: -10, x: 40, opacity: 0 }}
          whileInView={{ rotateY: 0, x: 0, opacity: 1 }}
          transition={{ duration: 1, ease: "easeOut" }}
          viewport={{ once: true, margin: "-100px" }}
          className="bg-stone-50 p-6 md:p-8 rounded-[2rem] border border-stone-200 shadow-2xl relative z-10"
        >
          {/* Stats Row */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
             {[
               { label: "Generated", val: "4", icon: null },
               { label: "Actions", val: "28", icon: null },
               { label: "Sentiment", val: "Positive", icon: <Smile size={20} className="text-emerald-500" /> },
               { label: "Insights", val: "12", icon: <Activity size={16} className="text-orange-500" /> }
             ].map((item, i) => (
                <Card key={i} noPadding className="p-4 flex flex-col justify-between h-24">
                  <span className="text-[10px] text-stone-400 font-bold uppercase tracking-wider">{item.label}</span>
                  <div className="flex items-center gap-1 text-stone-800 font-bold text-2xl md:text-xl lg:text-2xl">
                    {item.val} {item.icon}
                  </div>
                </Card>
             ))}
          </div>

          {/* Summaries Feed */}
          <div className="space-y-4">
            <SummaryCard 
              group="Group 42" 
              time="14:30" 
              tags={['Planning', 'Feedback']} 
              points={[
                "Q1 objectives prioritized for next sprint.",
                "Approval flow redesigned to reduce friction.",
                "Team requested more clarity on marketing budget."
              ]} 
            />
            <SummaryCard 
              group="Group 15" 
              time="10:15" 
              tags={['Launch', 'Sales']} 
              points={[
                "Product launch confirmed for Dec 15th.",
                "Inbound campaign approved by stakeholders.",
                "Sales team reporting higher than average lead quality."
              ]} 
            />
          </div>
          
          {/* Automation Suggestion */}
          <motion.div 
            initial={{ y: 20, opacity: 0 }}
            whileInView={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.5 }}
            className="mt-6 p-4 bg-orange-50 border border-orange-100 rounded-xl flex items-center justify-between"
          >
             <div className="flex items-center gap-3">
               <div className="w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center text-orange-600">
                 <Activity size={16} />
               </div>
               <div>
                 <p className="text-sm font-bold text-stone-800">Automated Daily Digest</p>
                 <p className="text-xs text-stone-500">Send to leaders at 6:00 PM</p>
               </div>
             </div>
             <TactileButton className="text-xs py-1 px-3">Enable</TactileButton>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
};
